-- INSERT-uri pentru categoria "Initiati"
INSERT INTO board_games (name, description, players, play_time, age_limit, complexity_rating, category) VALUES
('Abyss', 'Explorează adâncurile oceanului și preia controlul regatului subacvatic. Un joc de colecție de seturi și influență.', '2-4 jucători', '45 min', '14+', 2.0, 'Initiati'),
('Activity', 'Desenează, mimează sau explică pentru a-ți face echipa să ghicească! Perfect pentru petreceri.', '3-16 jucători', '30-60 min', '12+', 1.5, 'Initiati'),
('Alias', 'Explică rapid cuvintele și ajută-ți echipa să câștige.', '4+ jucători', '30-60 min', '10+', 1.5, 'Initiati'),
('Azul', 'Alege și combină plăcile de mozaic pentru a crea un design perfect. Un joc abstract de plasare de plăci.', '2-4 jucători', '30-45 min', '8+', 1.8, 'Initiati'),
('Bloodborne', 'Înfruntă monștri terifianți și supraviețuiește nopții în Yharnam.', '3-5 jucători', '30-60 min', '14+', 2.2, 'Initiati'),
('Bonsai', 'Crește și modelează cel mai frumos bonsai pentru a obține armonia perfectă.', '1-4 jucători', '30 min', '8+', 1.9, 'Initiati'),
('Cameleonul', 'Găsește impostorul sau ascunde-te bine printre ceilalți jucători!', '3-8 jucători', '15 min', '14+', 1.5, 'Initiati'),
('Carcassonne', 'Construiește orașe, drumuri și câmpii pentru a obține cele mai multe puncte.', '2-5 jucători', '35 min', '7+', 1.9, 'Initiati'),
('Carcassonne: Hanuri și Catedrale', 'Extinde-ți orașul cu hanuri și catedrale pentru a câștiga mai multe puncte.', '2-6 jucători', '40 min', '7+', 2.0, 'Initiati'),
('Cărți Escape: Contracronometru', 'Găsește indiciile și rezolvă puzzle-urile înainte să se termine timpul!', '1-6 jucători', '60 min', '12+', 2.3, 'Initiati'),
('Cărți Escape: În spatele cortinei', 'Descoperă secretele ascunse ale unui spectacol de magie misterios.', '1-6 jucători', '60 min', '12+', 2.3, 'Initiati'),
('Cărți Escape: Jaf în Veneția', 'Plănuiește și execută un jaf perfect într-un oraș plin de pericole.', '1-6 jucători', '60 min', '12+', 2.3, 'Initiati'),
('Cărți Escape: Misterul din El Dorado', 'Explorează jungla amazoniană și găsește comoara ascunsă a El Dorado.', '1-6 jucători', '60 min', '12+', 2.3, 'Initiati'),
('Cărți Escape: Soarta Londrei', 'Oprește complotul secret care amenință viitorul Londrei.', '1-6 jucători', '60 min', '12+', 2.3, 'Initiati'),
('Catan: Jocul de bază', 'Construiește așezări, schimbă resurse și cucerește insula Catan.', '3-4 jucători', '60-120 min', '10+', 2.0, 'Initiati'),
('Catan: Navigatorii', 'Explorează insule necunoscute și extinde-ți imperiul maritim.', '3-4 jucători', '90-120 min', '10+', 2.1, 'Initiati'),
('Catan: Negustori și Barbari', 'Controlează rute comerciale și apără-te de barbari necruțători.', '3-4 jucători', '90 min', '10+', 2.1, 'Initiati'),
('Catan: Orașe și Cavaleri', 'Dezvoltă orașe, antrenează cavaleri și protejează Catanul.', '3-4 jucători', '120 min', '12+', 2.4, 'Initiati'),
('Citadele', 'Alege roluri secrete și construiește un oraș grandios.', '2-8 jucători', '30-60 min', '10+', 2.0, 'Initiati'),
('Cóatl', 'Creează șerpi colorați și impresionează zeitățile aztece.', '1-4 jucători', '30-60 min', '10+', 1.9, 'Initiati'),
('Coup', 'Manipulează, blufează și elimină adversarii din joc.', '2-6 jucători', '15 min', '10+', 1.2, 'Initiati'),
('Curling', 'Testează-ți precizia și strategia într-un joc de curling pe masă.', '2-4 jucători', '30 min', '8+', 1.0, 'Initiati'),
('Decrypto', 'Transmite mesaje codificate fără ca adversarii să le descifreze.', '3-8 jucători', '30 min', '12+', 2.2, 'Initiati'),
('Dixit', 'Spune povești imaginative inspirate din ilustrații misterioase.', '3-8 jucători', '30 min', '8+', 1.0, 'Initiati'),
('Do I Know You?', 'Descoperă cât de bine îți cunoști prietenii prin întrebări surprinzătoare.', '2-6 jucători', '30 min', '10+', 1.0, 'Initiati'),
('Downforce', 'Licitează, pariază și pilotează mașini de curse spre victorie.', '2-6 jucători', '20-30 min', '8+', 1.9, 'Initiati'),
('Dungeon Decorators', 'Decorează cel mai impresionant dungeon pentru monștrii tăi preferați.', '2-4 jucători', '30-45 min', '10+', 2.0, 'Initiati'),
('Dungeon Fighter', 'Aruncă zaruri cu dexteritate pentru a învinge monștri periculoși.', '1-6 jucători', '45-60 min', '10+', 1.8, 'Initiati'),
('Exploding Kittens', 'Evită pisicile explozive și păcălește-ți adversarii.', '2-5 jucători', '15 min', '7+', 1.0, 'Initiati'),
('Flamecraft', 'Antrenează dragoni și dezvoltă cele mai prospere magazine magice.', '1-5 jucători', '60 min', '10+', 2.0, 'Initiati'),
('Galaxy Trucker', 'Construiește o navă spațială și supraviețuiește pericolelor din galaxie.', '2-4 jucători', '30-60 min', '10+', 2.2, 'Initiati'),
('Hellapagos', 'Supraviețuiește pe o insulă pustie și ia decizii dificile pentru echipaj.', '3-12 jucători', '20-40 min', '10+', 1.5, 'Initiati'),
('Hitster', 'Ghicește melodiile și creează cea mai bună linie temporală muzicală.', '2+ jucători', '30 min', '16+', 1.0, 'Initiati'),
('Jenga', 'Testează-ți îndemânarea extrăgând și stivuind blocuri din turn.', '1+ jucători', '5-15 min', '6+', 1.0, 'Initiati'),
('Klask', 'Un joc de dexteritate rapid, asemănător cu air hockey.', '2 jucători', '10 min', '8+', 1.0, 'Initiati'),
('Lost Ruins of Arnak', 'Explorează ruine antice, adună artefacte și descoperă secrete pierdute.', '1-4 jucători', '60-90 min', '12+', 2.5, 'Initiati'),
('Lost Ruins of Arnak: Lideri de expediție', 'O expansiune care adaugă personaje unice și strategii variate.', '1-4 jucători', '60-90 min', '12+', 2.6, 'Initiati'), -- ușor peste media inițiaților
('Love Letter', 'Transmite mesaje secrete și elimină rivalii pentru a câștiga inima prințesei.', '2-6 jucători', '20 min', '10+', 1.0, 'Initiati'),
('Marvel United', 'Adună-ți echipa de supereroi și luptă împotriva răufăcătorilor.', '1-4 jucători', '40 min', '10+', 1.5, 'Initiati'),
('Meadow', 'Explorează natura și creează o colecție de plante și animale.', '1-4 jucători', '60-90 min', '10+', 2.2, 'Initiati'),
('Monopoly', 'Cumpără, vinde și negociază pentru a deveni cel mai bogat jucător.', '2-6 jucători', '60-180 min', '8+', 1.5, 'Initiati'),
('Muza', 'Ghicește ilustrațiile folosind indicii creative și enigmatice.', '3-12 jucători', '30 min', '10+', 1.0, 'Initiati'),
('My Island', 'Construiește-ți insula și descoperă noi posibilități în fiecare joc.', '2-4 jucători', '30 min', '10+', 1.8, 'Initiati'),
('Mysterium', 'Rezolvă mistere folosind viziuni și indicii pentru a desluși o crimă.', '2-7 jucători', '42 min', '10+', 1.5, 'Initiati'),
('Nume de cod', 'Găsește cuvintele cod corecte folosind indicii subtile.', '2-8 jucători', '15 min', '10+', 1.2, 'Initiati'),
('Olympus Races', 'Participă la curse mitologice și folosește puterile zeilor pentru a câștiga.', '2-5 jucători', '20 min', '8+', 1.5, 'Initiati'),
('OMFG', 'Un joc de petrecere cu provocări nebune și momente haioase.', '3-6 jucători', '15-30 min', '16+', 1.0, 'Initiati'),
('Pădurea Aleasă', 'Explorează pădurea magică și descoperă creaturi fascinante.', '1-4 jucători', '30-45 min', '8+', 1.8, 'Initiati'),
('Povești Întunecate', 'Rezolvă mistere întunecate punând întrebări și descifrând indicii.', '2+ jucători', '15-30 min', '12+', 1.5, 'Initiati'),
('Ratoni Zgomotoși', 'Fă echipă cu ratonii și fură cele mai gustoase resturi.', '2-5 jucători', '20 min', '8+', 1.5, 'Initiati'),
('Risk', 'Cucerește teritorii și devino conducătorul suprem al lumii.', '2-6 jucători', '120 min', '10+', 2.2, 'Initiati'),
('Rummy', 'Formează combinații de cărți și câștigă puncte pentru a înfrunta adversarii.', '2-6 jucători', '30-60 min', '10+', 1.5, 'Initiati'),
('Saboteur', 'Colaborează pentru a găsi aurul, dar fii atent la sabotorii din echipă!', '3-10 jucători', '30 min', '8+', 1.2, 'Initiati'),
('Saboteur 2', 'Descoperă noi personaje și provocări în lupta pentru aur.', '2-12 jucători', '30 min', '8+', 1.3, 'Initiati'),
('Șah / Table', 'Joacă șah sau table și înfruntă-ți adversarul într-un duel de strategii.', '2 jucători', '10-60 min', '6+', 2.0, 'Initiati'),
('Secret Hitler', 'Descoperă cine este Hitler și cine sunt susținătorii săi în acest joc de trădare.', '5-10 jucători', '45 min', '13+', 1.8, 'Initiati'),
('Șeriful', 'Fii șeriful sau un bandit într-un oraș plin de pericole!', '3-6 jucători', '30-45 min', '10+', 1.5, 'Initiati'),
('SetUp', 'Creează cuvinte din literele disponibile și câștigă puncte.', '2-4 jucători', '30 min', '8+', 1.5, 'Initiati'),
('Shit Happens', 'Aranjează cele mai „neplăcute” scenarii într-un joc plin de umor.', '2+ jucători', '30 min', '18+', 1.0, 'Initiati'),
('Skull King', 'Joacă un joc de cărți cu licitații și provocări piratice.', '2-6 jucători', '30 min', '8+', 1.9, 'Initiati'),
('Splendor', 'Adună bijuterii și câștigă favoruri pentru a construi un imperiu.', '2-4 jucători', '30 min', '10+', 2.0, 'Initiati'),
('Stăpânul Inelelor: Frăția Inelului', 'Înfruntă pericolele alături de frăție pentru a distruge inelul puterii.', '2-5 jucători', '90-120 min', '12+', 2.3, 'Initiati'),
('Stella: Universul Dixit', 'Creează asociații între imagini pentru a câștiga puncte într-un joc plin de imaginație.', '3-6 jucători', '30 min', '8+', 1.0, 'Initiati'),
('The Crew', 'Colaborează cu echipa ta pentru a îndeplini misiuni în spațiu.', '2-5 jucători', '20 min', '10+', 1.8, 'Initiati'),
('The Crew: Mission Deep Sea', 'Continuă misiunile în adâncurile oceanului într-un joc cooperativ de cărți.', '2-5 jucători', '20 min', '10+', 1.9, 'Initiati'),
('Traveling', 'Creează-ți itinerarul și călătorește în jurul lumii pentru a aduna puncte.', '2-6 jucători', '30 min', '8+', 1.5, 'Initiati'),
('Trekking Through Time', 'Explorează istoria și adună cunoștințe pentru a deveni o legendă.', '2-4 jucători', '30-45 min', '10+', 2.0, 'Initiati'),
('Trio', 'Creează combinații de trei și câștigă puncte rapid!', '3-6 jucători', '15 min', '8+', 1.2, 'Initiati'),
('Trivia România', 'Pune-ți cunoștințele despre România la încercare într-un joc de trivia.', '2-6 jucători', '30 min', '10+', 1.0, 'Initiati'),
('Una Scurtă', 'Înfruntă-ți prietenii într-un joc rapid și plin de umor.', '3-6 jucători', '30 min', '18+', 1.0, 'Initiati'),
('UNO', 'Joacă și câștigă fiind primul care rămâne fără cărți.', '2-10 jucători', '30 min', '7+', 1.0, 'Initiati'),
('Unstable Unicorns', 'Construiește-ți regatul de unicorni și sabotează-ți adversarii.', '2-8 jucători', '30-45 min', '8+', 1.5, 'Initiati'),
('Vârcolacii', 'Găsește vârcolacii înainte să te devoreze!', '6-20 jucători', '30 min', '10+', 1.2, 'Initiati'),
('Werewolf', 'Descoperă cine sunt vârcolacii din sat și înfruntă-i înainte să fie prea târziu.', '6-20 jucători', '30 min', '10+', 1.2, 'Initiati'),
('Zestrea', 'Negociază și fă strategii pentru a deveni cel mai puternic nobil.', '3-6 jucători', '45-60 min', '14+', 2.0, 'Initiati'),
('21 Baker Street', 'Devino detectiv și rezolvă cazuri misterioase pe străzile Londrei.', '2-6 jucători', '30-60 min', '10+', 1.5, 'Initiati'),
('5 Minute Dungeon', 'Lucrează în echipă și scapă din dungeon înainte să expire timpul!', '2-5 jucători', '5 min', '8+', 1.0, 'Initiati'),
('5 Secunde', 'Răspunde rapid! Ai doar 5 secunde să dai trei exemple corecte.', '3-6 jucători', '5 min', '10+', 1.0, 'Initiati'),
('7 Wonders Architects', 'Construiește o minune a lumii și dezvoltă-ți civilizația.', '2-7 jucători', '25 min', '8+', 1.5, 'Initiati');

-- INSERT-uri pentru categoria "Maestri"
INSERT INTO board_games (name, description, players, play_time, age_limit, complexity_rating, category) VALUES
('Angel Fury', 'Război strategic între îngeri și demoni.', '2-4 jucători', '90-150 min', '14+', 3.0, 'Maestri'),
('Deal with the Devil', 'Fă alianțe și trădează pentru victorie.', '4 jucători', '120 min', '14+', 3.2, 'Maestri'),
('Destinies', 'Explorează și influențează lumea medievală.', '1-3 jucători', '90-150 min', '14+', 3.0, 'Maestri'),
('Dune: Imperium', 'Cucerește Arrakis prin strategie și putere.', '1-4 jucători', '60-120 min', '13+', 3.0, 'Maestri'),
('Eleven', 'Construiește și gestionează un club de fotbal.', '1-4 jucători', '60-120 min', '14+', 3.2, 'Maestri'),
('Everdell', 'Dezvoltă un oraș fermecat în pădure.', '1-4 jucători', '40-80 min', '10+', 2.8, 'Maestri'),
('God of War: Joc de cărți', 'Înfruntă monștri mitologici cu Kratos.', '1-4 jucători', '30-60 min', '14+', 2.5, 'Maestri'),
('Lying Pirates', 'Minte și păcălește pentru a câștiga.', '2-6 jucători', '30-45 min', '10+', 2.5, 'Maestri'),
('Sanctum', 'Învinge demoni într-un dungeon epic.', '2-4 jucători', '90-120 min', '12+', 3.0, 'Maestri'),
('Seasons', 'Folosește magia anotimpurilor pentru a câștiga.', '2-4 jucători', '60 min', '14+', 2.8, 'Maestri'),
('Stone Age', 'Condu un trib și supraviețuiește epocii de piatră.', '2-4 jucători', '60-90 min', '10+', 2.7, 'Maestri'),
('Wondrous Creatures', 'Creează ființe magice și explorează lumi noi.', '2-5 jucători', '30-60 min', '8+', 2.5, 'Maestri');

-- INSERT-uri pentru categoria "Legende"
INSERT INTO board_games (name, description, players, play_time, age_limit, complexity_rating, category) VALUES
('King''s Dilemma', 'Dezbate și influențează soarta regatului.', '3-5 jucători', '45-60 min', '14+', 4.0, 'Legende'),
('Roll Player Adventures', 'Creează un erou și trăiește aventuri epice.', '1-4 jucători', '90-150 min', '14+', 4.0, 'Legende'),
('Slay the Spire', 'Construiește un pachet și învinge inamicii.', '1-4 jucători', '45-90 min', '12+', 3.8, 'Legende'),
('The Witcher', 'Urmărește monștri și vânează recompense.', '1-5 jucători', '90-120 min', '14+', 4.2, 'Legende'),
('The Witcher: Mages', 'Manipulează magia și influențează lumea.', '1-5 jucători', '90-120 min', '14+', 4.3, 'Legende'),
('The Witcher: Skellige', 'Explorează insulele Skellige și supraviețuiește.', '1-5 jucători', '90-120 min', '14+', 4.3, 'Legende'),
('The Witcher: Legendary Hunt', 'Înfruntă cei mai periculoși monștri.', '1-5 jucători', '90-120 min', '14+', 4.4, 'Legende');