INSERT INTO products (name, description, image_url, is_active, buy_price, claim_value, stock, category) VALUES
-- Produse din structura de prețuri
('Alune Best (Un bol)', 'Alune sărate, bol mare.', 'https://railway.app/image/alune-best', TRUE, 6, 5, 100, 'SNACKS_SALT'),
('Burn Original, Doza', 'Băutură energizantă Burn Original, doză 250ml.', 'https://railway.app/image/burn-original', TRUE, 4, 3, 100, 'ENERGY_DRINK'),
('Cappy Nectar Pere, Sticla', 'Nectar de pere Cappy, sticlă 250ml.', 'https://railway.app/image/cappy-pere', TRUE, 5, 4, 100, 'SOFT_DRINK'),
('Cappy Nectar Piersica, Sticla', 'Nectar de piersici Cappy, sticlă 250ml.', 'https://railway.app/image/cappy-piersica', TRUE, 5, 4, 100, 'SOFT_DRINK'),
('Cappy Nectar Portocale Rosii, Sticla', 'Nectar de portocale roșii Cappy, sticlă 250ml.', 'https://railway.app/image/cappy-portocale-rosii', TRUE, 5, 4, 100, 'SOFT_DRINK'),
('Cappy Nectar Portocale, Sticla', 'Nectar de portocale Cappy, sticlă 250ml.', 'https://railway.app/image/cappy-portocale', TRUE, 5, 4, 100, 'SOFT_DRINK'),
('Cappy Nectar Visine, Sticla', 'Nectar de vișine Cappy, sticlă 250ml.', 'https://railway.app/image/cappy-visine', TRUE, 5, 4, 100, 'SOFT_DRINK'),
('Coca-Cola Gust Original, Sticla', 'Coca-Cola Gust Original, sticlă 250ml.', 'https://railway.app/image/coca-cola-original', TRUE, 4, 3, 100, 'SOFT_DRINK'),
('Coca-Cola Zero Zahar, Sticla', 'Coca-Cola Zero Zahăr, sticlă 250ml.', 'https://railway.app/image/coca-cola-zero', TRUE, 4, 3, 100, 'SOFT_DRINK'),
('Dorna, Apa minerala naturala carbogazoasa', 'Apă minerală carbogazoasă Dorna, sticlă 330ml.', 'https://railway.app/image/dorna-carbogazoasa', TRUE, 3, 2, 100, 'WATER'),
('Fanta Portocale, Sticla', 'Fanta Portocale, sticlă 250ml.', 'https://railway.app/image/fanta-portocale', TRUE, 4, 3, 100, 'SOFT_DRINK'),
('Fanta Struguri, Sticla', 'Fanta Struguri, sticlă 250ml.', 'https://railway.app/image/fanta-struguri', TRUE, 4, 3, 100, 'SOFT_DRINK'),
('Fuzetea Lamaie si Citronela, Sticla', 'Ice tea Fuzetea Lămâie și Citronelă, sticlă 250ml.', 'https://railway.app/image/fuzetea-lamaie', TRUE, 5, 4, 100, 'COFFEE_TEA'),
('Fuzetea Piersica si Hibiscus, Sticla', 'Ice tea Fuzetea Piersică și Hibiscus, sticlă 250ml.', 'https://railway.app/image/fuzetea-piersica', TRUE, 5, 4, 100, 'COFFEE_TEA'),
('Izvorul Alb, Apa minerala naturala plata, Sticla', 'Apă minerală plată Izvorul Alb, sticlă 330ml.', 'https://railway.app/image/izvorul-alb-plata', TRUE, 3, 2, 100, 'WATER'),
('Loto Chips Paprika', 'Chips-uri cu gust de Paprika, pungă 60g.', 'https://railway.app/image/loto-chips-paprika', TRUE, 3, 2, 100, 'SNACKS_SALT'),
('Loto Chips Sare', 'Chips-uri cu gust de Sare, pungă 60g.', 'https://railway.app/image/loto-chips-sare', TRUE, 3, 2, 100, 'SNACKS_SALT'),
('Loto Chips Smantana', 'Chips-uri cu gust de Smântână și Ceapă, pungă 60g.', 'https://railway.app/image/loto-chips-smantana', TRUE, 3, 2, 100, 'SNACKS_SALT'),
('Monster Pipeline Punch, Doza', 'Băutură energizantă Monster Pipeline Punch, doză 500ml.', 'https://railway.app/image/monster-pipeline', TRUE, 6, 5, 100, 'ENERGY_DRINK'),
('Portie Popcorn (Un bol)', 'Bol de popcorn mare.', 'https://railway.app/image/portie-popcorn', TRUE, 6, 5, 100, 'SNACKS_SALT'),
('Pufuleti Loto Naturali (o punga)', 'Pufuleți simpli Loto, pungă 45g.', 'https://railway.app/image/pufuleti-loto', TRUE, 1, 1, 100, 'SNACKS_SALT'),
('Schweppes Bitter Lemon, Sticla', 'Schweppes Bitter Lemon, sticlă 250ml.', 'https://railway.app/image/schweppes-bitter-lemon', TRUE, 4, 3, 100, 'SOFT_DRINK'),
('Schweppes Mandarin, Sticla', 'Schweppes Mandarin, sticlă 250ml.', 'https://railway.app/image/schweppes-mandarin', TRUE, 4, 3, 100, 'SOFT_DRINK'),
('Schweppes Pink Tonic, Sticla', 'Schweppes Pink Tonic, sticlă 250ml.', 'https://railway.app/image/schweppes-pink-tonic', TRUE, 4, 3, 100, 'SOFT_DRINK'),
('Schweppes Tonic Water, Sticla', 'Schweppes Tonic Water, sticlă 250ml.', 'https://railway.app/image/schweppes-tonic-water', TRUE, 4, 3, 100, 'SOFT_DRINK'),
('Sprite Lamaie si Lamaie Verde, Sticla', 'Sprite Lămâie și Lămâie Verde, sticlă 250ml.', 'https://railway.app/image/sprite-lamaie', TRUE, 4, 3, 100, 'SOFT_DRINK'),
('Cafea scurta Brewzeus Coffe', 'Espresso scurt Brewzeus Coffee, 30ml.', 'https://railway.app/image/cafea-scurta', TRUE, 4, 3, 100, 'COFFEE_TEA'),
('Cafea lunga Brewzeus Coffe', 'Cafea lungă Brewzeus Coffee, 120ml.', 'https://railway.app/image/cafea-lunga', TRUE, 5, 4, 100, 'COFFEE_TEA'),
('Cappucino Brewzeus Coffe', 'Cappucino Brewzeus Coffee, 120ml.', 'https://railway.app/image/cappucino', TRUE, 5, 4, 100, 'COFFEE_TEA'),
('Ceai', 'Diverse sortimente de ceai, 250ml.', 'https://railway.app/image/ceai', TRUE, 3, 2, 100, 'COFFEE_TEA'),
('Weissbier (Cearfisa)', 'Bere artizanală Weissbier (Cearfisa), 330ml, 5.2% alc.', 'https://railway.app/image/bere-weissbier', TRUE, 5, 4, 100, 'BEER'),
('Pale Ale (Cearfisa)', 'Bere artizanală Pale Ale (Cearfisa), 330ml, 5.5% alc.', 'https://railway.app/image/bere-pale-ale', TRUE, 5, 4, 100, 'BEER'),
('Pilsner (Cearfisa)', 'Bere artizanală Pilsner (Cearfisa), 330ml, 5.1% alc.', 'https://railway.app/image/bere-pilsner', TRUE, 5, 4, 100, 'BEER'),
('IPA (Cearfisa)', 'Bere artizanală IPA (Cearfisa), 330ml, 6% alc.', 'https://railway.app/image/bere-ipa', TRUE, 6, 5, 100, 'BEER'),
('Imperial Stout (Cearfisa)', 'Bere artizanală Imperial Stout (Cearfisa), 330ml, 9% alc.', 'https://railway.app/image/bere-imperial-stout', TRUE, 6, 5, 100, 'BEER'),
('Cola de munte (Bere fara alcool de la Cearfisa)', 'Bere fără alcool Cola de munte (Cearfisa), 330ml.', 'https://railway.app/image/bere-fara-alcool-cola-munte', TRUE, 4, 3, 100, 'BEER'),

-- Produse bazate pe imaginea cu tarife (Rata de conversie: 1 Leu = 0.4 Coins)
-- Taxa de intrare (25 lei) = 10 coins. Fără Claim Value (0) deoarece sunt taxe/abonamente.
('Taxa Intrare Standard', 'Plată la intrare: 25 lei / persoană. Valabilă pentru categoriile I, II și III (dacă nu e acoperită de abonament).', 'https://railway.app/image/taxa-intrare', TRUE, 10, 0, 1000, 'ENTRY_FEE'),
('Taxa Acces Jocuri Maestri (pe masa)', 'Acces jocuri din categoria "Maeștri" (Categoria II) - 50 lei pe masă, adițional taxei de intrare.', 'https://railway.app/image/taxa-jocuri-maestri', TRUE, 20, 0, 1000, 'ENTRY_FEE'),
('Abonament Lunar Legende', 'Abonament lunar pentru acces jocuri "Legende" (Categoria III). Include acces la toate jocurile și bonus zilnic.', 'https://railway.app/image/abonament-legende', TRUE, 140, 0, 1000, 'SUBSCRIPTION');